-- document-id: DATA-07
-- PostgreSQL 16 canonical bootstrap schema. UUIDv7 values are generated by the application.

BEGIN;

CREATE TYPE workspace_status AS ENUM ('ACTIVE', 'DELETION_SCHEDULED', 'PURGING', 'DELETED');
CREATE TYPE membership_role AS ENUM ('MEMBER', 'ADMIN', 'OWNER');
CREATE TYPE membership_status AS ENUM ('ACTIVE', 'SUSPENDED', 'REMOVED');
CREATE TYPE subject_kind AS ENUM ('USER', 'GROUP');
CREATE TYPE document_access AS ENUM ('NO_ACCESS', 'VIEWER', 'CONTRIBUTOR', 'EDITOR');
CREATE TYPE document_status AS ENUM ('ACTIVE', 'TRASHED', 'PURGING');
CREATE TYPE publish_mode AS ENUM ('DIRECT', 'REVIEW_REQUIRED');
CREATE TYPE discussion_status AS ENUM ('OPEN', 'CLOSED');
CREATE TYPE review_status AS ENUM ('REQUESTED', 'APPROVED', 'CHANGES_REQUESTED', 'CANCELLED', 'INVALIDATED');
CREATE TYPE review_decision AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUESTED');
CREATE TYPE vocabulary_status AS ENUM ('ACTIVE', 'DEPRECATED');
CREATE TYPE ai_job_status AS ENUM ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT');
CREATE TYPE proposal_status AS ENUM ('OPEN', 'APPLIED', 'REJECTED', 'STALE', 'CANCELLED');
CREATE TYPE file_status AS ENUM ('UPLOADING', 'VALIDATING', 'READY', 'FAILED', 'DELETED');
CREATE TYPE job_status AS ENUM ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'DEAD_LETTER');
CREATE TYPE event_audience_kind AS ENUM ('INTERNAL', 'WORKSPACE', 'ADMIN', 'USER', 'DOCUMENT');

CREATE TABLE users (
  id uuid PRIMARY KEY,
  identity_issuer text NOT NULL DEFAULT 'https://accounts.google.com',
  google_subject text NOT NULL,
  email text NOT NULL,
  email_normalized text GENERATED ALWAYS AS (lower(email)) STORED,
  display_name text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 200),
  locale text NOT NULL DEFAULT 'ko' CHECK (locale IN ('ko', 'en')),
  timezone text NOT NULL DEFAULT 'Asia/Seoul',
  theme text NOT NULL DEFAULT 'SYSTEM' CHECK (theme IN ('LIGHT', 'DARK', 'SYSTEM')),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (identity_issuer, google_subject)
);
CREATE INDEX users_email_normalized_idx ON users (email_normalized);

CREATE TABLE login_flows (
  state_hash bytea PRIMARY KEY CHECK (octet_length(state_hash) = 32),
  marker_hash bytea NOT NULL CHECK (octet_length(marker_hash) = 32),
  hash_key_id text NOT NULL CHECK (hash_key_id ~ '^[A-Za-z0-9._-]{1,64}$'),
  nonce_hash bytea NOT NULL CHECK (octet_length(nonce_hash) = 32),
  pkce_verifier text NOT NULL CHECK (char_length(pkce_verifier) BETWEEN 43 AND 128),
  return_to text NOT NULL CHECK (char_length(return_to) BETWEEN 1 AND 2048),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  CHECK (expires_at > created_at),
  CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX login_flows_expiry_idx ON login_flows (expires_at);

CREATE TABLE sessions (
  id_hash bytea PRIMARY KEY CHECK (octet_length(id_hash) = 32),
  hash_key_id text NOT NULL CHECK (hash_key_id ~ '^[A-Za-z0-9._-]{1,64}$'),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rotated_from_hash bytea UNIQUE,
  last_seen_at timestamptz NOT NULL,
  idle_expires_at timestamptz NOT NULL,
  absolute_expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (last_seen_at >= created_at),
  CHECK (idle_expires_at >= last_seen_at),
  CHECK (absolute_expires_at >= idle_expires_at),
  CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX sessions_active_user_idx ON sessions (user_id, idle_expires_at, absolute_expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE user_command_receipts (
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operation_id text NOT NULL CHECK (char_length(operation_id) BETWEEN 1 AND 100),
  key text NOT NULL CHECK (char_length(key) BETWEEN 16 AND 128),
  request_hash text NOT NULL CHECK (request_hash ~ '^[a-f0-9]{64}$'),
  response_json jsonb,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (user_id, operation_id, key),
  CHECK (expires_at > created_at)
);
CREATE INDEX user_command_receipts_expiry_idx ON user_command_receipts (expires_at);

CREATE TABLE workspaces (
  id uuid PRIMARY KEY,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
  status workspace_status NOT NULL DEFAULT 'ACTIVE',
  default_publish_mode publish_mode NOT NULL DEFAULT 'DIRECT',
  delete_after timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'ACTIVE' AND delete_after IS NULL) OR
         (status IN ('DELETION_SCHEDULED', 'PURGING', 'DELETED') AND delete_after IS NOT NULL))
);

CREATE TABLE memberships (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role membership_role NOT NULL DEFAULT 'MEMBER',
  status membership_status NOT NULL DEFAULT 'ACTIVE',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  joined_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  PRIMARY KEY (workspace_id, user_id),
  CHECK ((status = 'REMOVED') = (removed_at IS NOT NULL))
);
CREATE INDEX memberships_active_user_idx ON memberships (user_id, workspace_id) WHERE status = 'ACTIVE';

CREATE TABLE writing_configurations (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  baseline_version text NOT NULL,
  overrides_json jsonb NOT NULL,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE ai_configurations (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  provider text NOT NULL,
  model text NOT NULL,
  user_concurrency_limit smallint NOT NULL CHECK (user_concurrency_limit BETWEEN 1 AND 20),
  workspace_concurrency_limit smallint NOT NULL CHECK (workspace_concurrency_limit BETWEEN 1 AND 200),
  monthly_budget_microunits bigint NOT NULL CHECK (monthly_budget_microunits >= 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (user_concurrency_limit <= workspace_concurrency_limit)
);

CREATE TABLE ai_usage_daily (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  estimated_microunits bigint NOT NULL DEFAULT 0 CHECK (estimated_microunits >= 0),
  job_count bigint NOT NULL DEFAULT 0 CHECK (job_count >= 0),
  PRIMARY KEY (workspace_id, usage_date, provider, model)
);

CREATE TABLE invitations (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email text NOT NULL,
  email_normalized text GENERATED ALWAYS AS (lower(email)) STORED,
  role membership_role NOT NULL DEFAULT 'MEMBER' CHECK (role <> 'OWNER'),
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  token_key_id text NOT NULL CHECK (char_length(token_key_id) BETWEEN 1 AND 64),
  invited_by uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, invited_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (expires_at > created_at),
  CHECK (accepted_at IS NULL OR revoked_at IS NULL)
);
CREATE UNIQUE INDEX invitations_active_email_idx ON invitations (workspace_id, email_normalized)
  WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE TABLE groups (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
  name_normalized text GENERATED ALWAYS AS (lower(name)) STORED,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id)
);
CREATE UNIQUE INDEX groups_active_name_idx ON groups (workspace_id, name_normalized) WHERE deleted_at IS NULL;

CREATE TABLE group_members (
  workspace_id uuid NOT NULL,
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, group_id, user_id),
  FOREIGN KEY (workspace_id, group_id) REFERENCES groups(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE
);

CREATE TABLE documents (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  parent_id uuid,
  rank text COLLATE "C" NOT NULL CHECK (rank ~ '^[0-9A-Za-z]{32}$'),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
  status document_status NOT NULL DEFAULT 'ACTIVE',
  current_version_id uuid,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  permission_revision bigint NOT NULL DEFAULT 0 CHECK (permission_revision >= 0),
  policy_revision bigint NOT NULL DEFAULT 0 CHECK (policy_revision >= 0),
  trashed_at timestamptz,
  purge_after timestamptz,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, parent_id) REFERENCES documents(workspace_id, id) DEFERRABLE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (parent_id IS NULL OR parent_id <> id),
  CHECK ((status = 'ACTIVE' AND trashed_at IS NULL AND purge_after IS NULL) OR
         (status IN ('TRASHED', 'PURGING') AND trashed_at IS NOT NULL AND purge_after IS NOT NULL)),
  CHECK (purge_after IS NULL OR purge_after >= trashed_at)
);
CREATE UNIQUE INDEX documents_sibling_rank_idx ON documents (workspace_id, parent_id, rank) WHERE status <> 'PURGING';
CREATE INDEX documents_tree_idx ON documents (workspace_id, parent_id, status, rank);

CREATE TABLE workspace_document_revisions (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  tree_revision bigint NOT NULL DEFAULT 0 CHECK (tree_revision >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE FUNCTION initialize_workspace_document_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO workspace_document_revisions(workspace_id) VALUES(NEW.id);
  RETURN NEW;
END;
$$;
CREATE TRIGGER workspace_document_revision_initialize
  AFTER INSERT ON workspaces
  FOR EACH ROW EXECUTE FUNCTION initialize_workspace_document_revision();

CREATE TABLE document_move_previews (
  token_hash bytea PRIMARY KEY CHECK (octet_length(token_hash) = 32),
  workspace_id uuid NOT NULL,
  actor_user_id uuid NOT NULL,
  document_id uuid NOT NULL,
  claims_json jsonb NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, actor_user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  CHECK (jsonb_typeof(claims_json) = 'object'),
  CHECK (expires_at > created_at)
);
CREATE INDEX document_move_previews_expiry_idx ON document_move_previews (expires_at);

CREATE TABLE workspace_access_revisions (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  permission_revision bigint NOT NULL DEFAULT 0 CHECK (permission_revision >= 0),
  policy_revision bigint NOT NULL DEFAULT 0 CHECK (policy_revision >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE permission_grants (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  subject_kind subject_kind NOT NULL,
  subject_id uuid NOT NULL,
  access document_access NOT NULL,
  can_manage boolean NOT NULL DEFAULT false,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  granted_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, document_id, subject_kind, subject_id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, granted_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (NOT can_manage OR access = 'EDITOR')
);
CREATE INDEX permission_grants_resolve_idx ON permission_grants (workspace_id, subject_kind, subject_id, document_id);

CREATE TABLE publish_policies (
  document_id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  mode publish_mode NOT NULL,
  required_approvals smallint NOT NULL DEFAULT 0 CHECK (required_approvals BETWEEN 0 AND 20),
  reviewer_rule jsonb NOT NULL DEFAULT '{"kind":"ANY_EDITOR"}'::jsonb,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((mode = 'DIRECT' AND required_approvals = 0) OR (mode = 'REVIEW_REQUIRED' AND required_approvals > 0))
);

CREATE TABLE published_versions (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  number bigint NOT NULL CHECK (number > 0),
  content_json jsonb NOT NULL,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  content_fingerprint char(64) NOT NULL CHECK (content_fingerprint ~ '^[a-f0-9]{64}$'),
  based_on_version_id uuid,
  source_draft_revision bigint NOT NULL CHECK (source_draft_revision >= 0),
  publisher_id uuid NOT NULL,
  summary text NOT NULL CHECK (char_length(summary) BETWEEN 1 AND 1000 AND summary = btrim(summary)),
  published_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  UNIQUE (document_id, number),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (workspace_id, based_on_version_id) REFERENCES published_versions(workspace_id, id),
  FOREIGN KEY (workspace_id, publisher_id) REFERENCES memberships(workspace_id, user_id)
);
ALTER TABLE documents ADD CONSTRAINT documents_current_version_fk
  FOREIGN KEY (workspace_id, current_version_id) REFERENCES published_versions(workspace_id, id) DEFERRABLE;

CREATE TABLE drafts (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL UNIQUE,
  base_version_id uuid,
  content_json jsonb NOT NULL,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, base_version_id) REFERENCES published_versions(workspace_id, id),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE edit_leases (
  document_id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  holder_user_id uuid NOT NULL,
  client_instance_id uuid NOT NULL,
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at timestamptz NOT NULL,
  released_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  acquired_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, holder_user_id) REFERENCES memberships(workspace_id, user_id),
  CHECK (released_at IS NULL OR released_at >= acquired_at)
);
CREATE INDEX edit_leases_expiry_idx ON edit_leases (expires_at);

CREATE TABLE version_context (
  version_id uuid PRIMARY KEY REFERENCES published_versions(id) ON DELETE CASCADE,
  review_snapshot_json jsonb NOT NULL,
  discussion_ids uuid[] NOT NULL DEFAULT '{}',
  source_revision bigint NOT NULL CHECK (source_revision >= 0)
);

CREATE TABLE public_links (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at timestamptz,
  revoked_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (expires_at IS NULL OR expires_at > created_at),
  CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX public_links_active_document_idx ON public_links (workspace_id, document_id)
  WHERE revoked_at IS NULL;

CREATE TABLE discussions (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
  status discussion_status NOT NULL DEFAULT 'OPEN',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status = 'CLOSED') = (closed_at IS NOT NULL))
);
CREATE INDEX discussions_document_idx ON discussions (workspace_id, document_id, status, created_at DESC);

CREATE TABLE discussion_topics (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  discussion_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind IN ('TEXT', 'DOCUMENT', 'REGION', 'EXTERNAL')),
  target_json jsonb NOT NULL,
  label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 500),
  rank text NOT NULL,
  UNIQUE (discussion_id, rank),
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  discussion_id uuid NOT NULL,
  author_id uuid NOT NULL,
  body_json jsonb NOT NULL,
  mention_user_ids uuid[] NOT NULL DEFAULT '{}',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, author_id) REFERENCES memberships(workspace_id, user_id)
);
CREATE INDEX messages_discussion_idx ON messages (workspace_id, discussion_id, created_at, id);

CREATE TABLE message_revisions (
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  revision bigint NOT NULL CHECK (revision > 0),
  body_json jsonb NOT NULL,
  mention_user_ids uuid[] NOT NULL DEFAULT '{}',
  deleted_at timestamptz,
  edited_by uuid NOT NULL REFERENCES users(id),
  edited_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, revision)
);

CREATE TABLE reviews (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  draft_id uuid NOT NULL,
  draft_revision bigint NOT NULL CHECK (draft_revision >= 0),
  policy_snapshot_json jsonb NOT NULL,
  status review_status NOT NULL DEFAULT 'REQUESTED',
  requested_by uuid NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, requested_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status = 'REQUESTED') = (resolved_at IS NULL))
);
CREATE UNIQUE INDEX reviews_active_document_idx ON reviews (document_id) WHERE status = 'REQUESTED';

CREATE TABLE review_assignments (
  workspace_id uuid NOT NULL,
  review_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  decision review_decision NOT NULL DEFAULT 'PENDING',
  decided_at timestamptz,
  discussion_id uuid,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (review_id, reviewer_id),
  FOREIGN KEY (workspace_id, review_id) REFERENCES reviews(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, reviewer_id) REFERENCES memberships(workspace_id, user_id),
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id),
  CHECK ((decision = 'PENDING') = (decided_at IS NULL))
);

CREATE TABLE review_decision_revisions (
  workspace_id uuid NOT NULL,
  review_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  revision bigint NOT NULL CHECK (revision > 0),
  decision review_decision NOT NULL,
  discussion_id uuid,
  decided_at timestamptz NOT NULL,
  PRIMARY KEY (review_id, reviewer_id, revision),
  FOREIGN KEY (workspace_id, review_id) REFERENCES reviews(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, reviewer_id) REFERENCES memberships(workspace_id, user_id),
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id)
);

CREATE TABLE inbox_items (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  source_key text NOT NULL,
  target_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  resolved_at timestamptz,
  UNIQUE (workspace_id, user_id, source_key),
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE
);
CREATE INDEX inbox_items_unresolved_idx ON inbox_items (workspace_id, user_id, created_at DESC)
  WHERE resolved_at IS NULL;

CREATE FUNCTION retention_mutation_allowed() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT current_user = 'adoc_retention'
    OR (current_user = 'postgres' AND current_setting('adoc.retention_context', true) = 'on')
$$;

CREATE OR REPLACE FUNCTION reject_message_revision_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF retention_mutation_allowed() AND TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RAISE EXCEPTION 'message revisions are immutable';
END $$;
CREATE TRIGGER message_revisions_immutable BEFORE UPDATE OR DELETE ON message_revisions
FOR EACH ROW EXECUTE FUNCTION reject_message_revision_mutation();

CREATE OR REPLACE FUNCTION reject_review_decision_revision_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF retention_mutation_allowed() AND TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RAISE EXCEPTION 'review decision revisions are immutable';
END $$;
CREATE TRIGGER review_decision_revisions_immutable BEFORE UPDATE OR DELETE ON review_decision_revisions
FOR EACH ROW EXECUTE FUNCTION reject_review_decision_revision_mutation();

CREATE TABLE references_graph (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  source_kind text NOT NULL CHECK (source_kind = 'DOCUMENT'),
  source_id uuid NOT NULL,
  target_kind text NOT NULL,
  target_id text NOT NULL,
  target_region_json jsonb,
  source_region_json jsonb NOT NULL,
  snapshot_json jsonb NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, source_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((target_kind = 'REGION') = (target_region_json IS NOT NULL))
);
CREATE INDEX references_target_idx ON references_graph (workspace_id, target_kind, target_id, created_at DESC, id DESC)
  WHERE deleted_at IS NULL;

CREATE TABLE vocabulary_concepts (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  canonical_term text NOT NULL CHECK (char_length(canonical_term) BETWEEN 1 AND 200),
  definition text NOT NULL CHECK (char_length(definition) BETWEEN 1 AND 5000),
  status vocabulary_status NOT NULL DEFAULT 'ACTIVE',
  replacement_concept_id uuid,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  FOREIGN KEY (workspace_id, replacement_concept_id) REFERENCES vocabulary_concepts(workspace_id, id),
  CHECK (status <> 'ACTIVE' OR replacement_concept_id IS NULL)
);

CREATE TABLE vocabulary_terms (
  workspace_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  term text NOT NULL,
  normalized_term text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('CANONICAL', 'SYNONYM', 'PROHIBITED')),
  PRIMARY KEY (concept_id, normalized_term),
  FOREIGN KEY (workspace_id, concept_id) REFERENCES vocabulary_concepts(workspace_id, id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX vocabulary_terms_workspace_unique_idx ON vocabulary_terms (workspace_id, normalized_term);

CREATE TABLE vocabulary_concept_revisions (
  workspace_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  revision bigint NOT NULL CHECK (revision > 0),
  canonical_term text NOT NULL,
  definition text NOT NULL,
  status vocabulary_status NOT NULL,
  replacement_concept_id uuid,
  terms_json jsonb NOT NULL,
  change_reason text,
  changed_by uuid NOT NULL,
  changed_at timestamptz NOT NULL,
  PRIMARY KEY (concept_id, revision),
  FOREIGN KEY (workspace_id, concept_id) REFERENCES vocabulary_concepts(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, changed_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE OR REPLACE FUNCTION reject_vocabulary_revision_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF retention_mutation_allowed() AND TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RAISE EXCEPTION 'vocabulary concept revisions are immutable';
END $$;
CREATE TRIGGER vocabulary_concept_revisions_immutable BEFORE UPDATE OR DELETE ON vocabulary_concept_revisions
FOR EACH ROW EXECUTE FUNCTION reject_vocabulary_revision_mutation();

CREATE TABLE ai_jobs (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL,
  target_json jsonb NOT NULL,
  expected_revision bigint NOT NULL CHECK (expected_revision >= 0),
  context_fingerprint text NOT NULL CHECK (context_fingerprint ~ '^[a-f0-9]{64}$'),
  context_metadata_json jsonb NOT NULL,
  request_key text NOT NULL CHECK (char_length(request_key) BETWEEN 8 AND 200),
  runtime_job_id uuid UNIQUE,
  status ai_job_status NOT NULL DEFAULT 'QUEUED',
  priority smallint NOT NULL CHECK (priority BETWEEN 0 AND 100),
  provider text NOT NULL,
  model text NOT NULL,
  usage_json jsonb,
  error_code text,
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, user_id, request_key),
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')) = (completed_at IS NOT NULL))
);
CREATE INDEX ai_jobs_queue_idx ON ai_jobs (priority DESC, created_at) WHERE status = 'QUEUED';
CREATE INDEX ai_jobs_user_active_idx ON ai_jobs (workspace_id, user_id, status)
  WHERE status IN ('QUEUED', 'RUNNING');

CREATE TABLE ai_context_sources (
  job_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  source_kind text NOT NULL,
  source_id text NOT NULL,
  stable_id text NOT NULL,
  authority text NOT NULL,
  include_reason text NOT NULL CHECK (include_reason IN ('CURRENT_TARGET', 'EXPLICIT_REFERENCE', 'DISCUSSION_CONTEXT', 'VOCABULARY_POLICY', 'RETRIEVED_RELATED', 'USER_PROVIDED')),
  snapshot_hash text NOT NULL CHECK (snapshot_hash ~ '^[a-f0-9]{64}$'),
  snapshot_text text NOT NULL CHECK (octet_length(snapshot_text) <= 65536),
  source_revision bigint NOT NULL CHECK (source_revision >= 0),
  permission_key text CHECK (permission_key IS NULL OR permission_key ~ '^[a-f0-9]{64}$'),
  included boolean NOT NULL,
  metadata_json jsonb NOT NULL,
  PRIMARY KEY (job_id, ordinal),
  FOREIGN KEY (workspace_id, job_id) REFERENCES ai_jobs(workspace_id, id) ON DELETE CASCADE
);

CREATE TABLE ai_results (
  job_id uuid PRIMARY KEY REFERENCES ai_jobs(id) ON DELETE CASCADE,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  result_json jsonb NOT NULL,
  validation_json jsonb NOT NULL,
  completed_at timestamptz NOT NULL
);

CREATE TABLE proposals (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  job_id uuid NOT NULL UNIQUE,
  document_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  base_revision bigint NOT NULL CHECK (base_revision >= 0),
  operations_json jsonb NOT NULL,
  writing_rule_version text NOT NULL,
  vocabulary_revision bigint NOT NULL CHECK (vocabulary_revision >= 0),
  validation_json jsonb NOT NULL,
  status proposal_status NOT NULL DEFAULT 'OPEN',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  applied_revision bigint,
  applied_operation_ids uuid[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  FOREIGN KEY (workspace_id, job_id) REFERENCES ai_jobs(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, owner_user_id) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status = 'OPEN') = (resolved_at IS NULL)),
  CHECK ((status = 'APPLIED') = (applied_revision IS NOT NULL))
);

CREATE TABLE file_assets (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  storage_key text NOT NULL,
  original_name text NOT NULL CHECK (char_length(original_name) BETWEEN 1 AND 500),
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  checksum_sha256 text NOT NULL CHECK (checksum_sha256 ~ '^[a-f0-9]{64}$'),
  status file_status NOT NULL DEFAULT 'UPLOADING',
  detected_mime_type text,
  failure_code text,
  uploaded_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  ready_at timestamptz,
  deleted_at timestamptz,
  purge_after timestamptz,
  gc_claimed_at timestamptz,
  byte_deleted_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, storage_key),
  FOREIGN KEY (workspace_id, uploaded_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status IN ('UPLOADING', 'VALIDATING', 'FAILED') AND ready_at IS NULL) OR
         (status IN ('READY', 'DELETED') AND ready_at IS NOT NULL)),
  CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL AND purge_after IS NOT NULL))
);
CREATE INDEX file_assets_gc_idx ON file_assets (workspace_id, purge_after) WHERE status = 'DELETED';

CREATE TABLE file_upload_sessions (
  asset_id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  token_hash bytea NOT NULL CHECK (octet_length(token_hash) = 32),
  token_key_id text NOT NULL CHECK (char_length(token_key_id) BETWEEN 1 AND 100),
  expires_at timestamptz NOT NULL,
  uploaded_at timestamptz,
  validation_key text,
  validation_request_hash text,
  completed_at timestamptz,
  FOREIGN KEY (workspace_id, asset_id) REFERENCES file_assets(workspace_id, id) ON DELETE CASCADE,
  CHECK (completed_at IS NULL OR uploaded_at IS NOT NULL),
  CHECK ((validation_key IS NULL) = (validation_request_hash IS NULL))
);

CREATE TABLE file_references (
  workspace_id uuid NOT NULL,
  asset_id uuid NOT NULL,
  owner_kind text NOT NULL CHECK (owner_kind IN ('DRAFT', 'PUBLISHED_VERSION', 'MESSAGE', 'VOCABULARY')),
  owner_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (asset_id, owner_kind, owner_id),
  FOREIGN KEY (workspace_id, asset_id) REFERENCES file_assets(workspace_id, id) ON DELETE CASCADE
);
CREATE INDEX file_references_owner_idx ON file_references (workspace_id, owner_kind, owner_id);

CREATE TABLE workspace_sequences (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  next_audit_sequence bigint NOT NULL DEFAULT 1 CHECK (next_audit_sequence > 0),
  next_stream_sequence bigint NOT NULL DEFAULT 1 CHECK (next_stream_sequence > 0),
  next_projection_sequence bigint NOT NULL DEFAULT 1 CHECK (next_projection_sequence > 0)
);

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  sequence bigint NOT NULL CHECK (sequence > 0),
  actor_json jsonb NOT NULL,
  action text NOT NULL,
  target_json jsonb NOT NULL,
  before_json jsonb,
  after_json jsonb,
  metadata_json jsonb NOT NULL,
  correlation_id text NOT NULL CHECK (char_length(correlation_id) BETWEEN 8 AND 128),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  redacted_at timestamptz,
  UNIQUE (workspace_id, sequence)
);
CREATE INDEX audit_events_target_idx ON audit_events (workspace_id, (target_json->>'kind'), (target_json->>'id'), sequence DESC);

CREATE TABLE jobs (
  id uuid PRIMARY KEY,
  workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('OUTBOX_TO_STREAM', 'OUTBOX_TO_SEARCH', 'AI_RUNTIME')),
  payload_json jsonb NOT NULL CHECK (octet_length(payload_json::text) <= 65536),
  dedupe_key text NOT NULL CHECK (char_length(dedupe_key) BETWEEN 1 AND 200),
  status job_status NOT NULL DEFAULT 'QUEUED',
  priority smallint NOT NULL DEFAULT 50 CHECK (priority BETWEEN 0 AND 100),
  sequence bigint NOT NULL DEFAULT 1 CHECK (sequence > 0),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  run_after timestamptz NOT NULL DEFAULT now(),
  lease_owner text,
  lease_until timestamptz,
  cancel_requested_at timestamptz,
  last_error_code text,
  correlation_id text NOT NULL CHECK (char_length(correlation_id) BETWEEN 8 AND 128),
  replay_of_job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (kind, dedupe_key),
  CHECK ((lease_owner IS NULL) = (lease_until IS NULL)),
  CHECK (attempt <= max_attempts),
  CHECK ((status IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'DEAD_LETTER')) = (completed_at IS NOT NULL)),
  CHECK (status IN ('RUNNING', 'CANCEL_REQUESTED') OR lease_owner IS NULL),
  CHECK ((status = 'CANCEL_REQUESTED') = (cancel_requested_at IS NOT NULL) OR status IN ('CANCELLED'))
);
CREATE INDEX jobs_dequeue_idx ON jobs (priority DESC, run_after, id) WHERE status = 'QUEUED';
ALTER TABLE ai_jobs ADD CONSTRAINT ai_jobs_runtime_job_fk
  FOREIGN KEY (runtime_job_id) REFERENCES jobs(id) ON DELETE SET NULL;
CREATE INDEX jobs_expired_lease_idx ON jobs (lease_until, id) WHERE status IN ('RUNNING', 'CANCEL_REQUESTED');

CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  aggregate_kind text NOT NULL,
  aggregate_id uuid NOT NULL,
  sequence bigint NOT NULL CHECK (sequence > 0),
  event_type text NOT NULL,
  event_version integer NOT NULL CHECK (event_version > 0),
  projection_sequence bigint NOT NULL CHECK (projection_sequence > 0),
  payload_json jsonb NOT NULL CHECK (octet_length(payload_json::text) <= 65536),
  audience_kind event_audience_kind NOT NULL,
  audience_id uuid,
  minimum_access document_access,
  correlation_id text NOT NULL CHECK (char_length(correlation_id) BETWEEN 8 AND 128),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  UNIQUE (aggregate_kind, aggregate_id, sequence),
  UNIQUE (workspace_id, projection_sequence),
  CHECK (
    (audience_kind IN ('INTERNAL', 'WORKSPACE', 'ADMIN') AND audience_id IS NULL AND minimum_access IS NULL)
    OR (audience_kind = 'USER' AND audience_id IS NOT NULL AND minimum_access IS NULL)
    OR (audience_kind = 'DOCUMENT' AND audience_id IS NOT NULL AND minimum_access IN ('VIEWER', 'CONTRIBUTOR', 'EDITOR'))
  )
);
CREATE INDEX outbox_unpublished_idx ON outbox_events (occurred_at, id) WHERE published_at IS NULL;

CREATE TABLE consumer_receipts (
  consumer text NOT NULL,
  event_id uuid NOT NULL REFERENCES outbox_events(id) ON DELETE CASCADE,
  processed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (consumer, event_id)
);

CREATE TABLE search_projection_rebuilds (
  id uuid PRIMARY KEY,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  generation bigint NOT NULL CHECK (generation > 0),
  status text NOT NULL CHECK (status IN ('BUILDING', 'CATCHING_UP', 'VALIDATING', 'ACTIVE', 'FAILED')),
  snapshot_watermark_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  replayed_through_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_code text,
  started_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (schema_version, generation),
  CHECK ((status IN ('ACTIVE', 'FAILED')) = (completed_at IS NOT NULL))
);
CREATE UNIQUE INDEX search_projection_rebuild_active_idx ON search_projection_rebuilds ((true))
  WHERE status IN ('BUILDING', 'CATCHING_UP', 'VALIDATING');

CREATE TABLE workspace_stream_events (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  sequence bigint NOT NULL CHECK (sequence > 0),
  outbox_event_id uuid NOT NULL REFERENCES outbox_events(id) ON DELETE CASCADE,
  aggregate_id uuid NOT NULL,
  event_type text NOT NULL,
  event_version integer NOT NULL CHECK (event_version > 0),
  payload_json jsonb NOT NULL CHECK (octet_length(payload_json::text) <= 65536),
  audience_kind event_audience_kind NOT NULL CHECK (audience_kind <> 'INTERNAL'),
  audience_id uuid,
  minimum_access document_access,
  correlation_id text NOT NULL CHECK (char_length(correlation_id) BETWEEN 8 AND 128),
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  UNIQUE (workspace_id, sequence),
  UNIQUE (outbox_event_id),
  CHECK (expires_at > created_at),
  CHECK (
    (audience_kind IN ('WORKSPACE', 'ADMIN') AND audience_id IS NULL AND minimum_access IS NULL)
    OR (audience_kind = 'USER' AND audience_id IS NOT NULL AND minimum_access IS NULL)
    OR (audience_kind = 'DOCUMENT' AND audience_id IS NOT NULL AND minimum_access IN ('VIEWER', 'CONTRIBUTOR', 'EDITOR'))
  )
);
CREATE INDEX workspace_stream_replay_idx ON workspace_stream_events (workspace_id, sequence, id);
CREATE INDEX workspace_stream_expiry_idx ON workspace_stream_events (expires_at, id);

CREATE FUNCTION reject_stream_event_update() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workspace stream events are immutable';
END;
$$;
CREATE TRIGGER workspace_stream_events_immutable BEFORE UPDATE ON workspace_stream_events
FOR EACH ROW EXECUTE FUNCTION reject_stream_event_update();

CREATE TABLE idempotency_keys (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES users(id),
  operation_id text NOT NULL,
  key text NOT NULL,
  request_hash text NOT NULL CHECK (request_hash ~ '^[a-f0-9]{64}$'),
  response_status integer,
  response_json jsonb,
  locked_until timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, actor_id, operation_id, key),
  CHECK ((response_status IS NULL) = (response_json IS NULL)),
  CHECK (expires_at > created_at)
);
CREATE INDEX idempotency_expiry_idx ON idempotency_keys (expires_at);

CREATE TABLE purge_ledger (
  id uuid PRIMARY KEY,
  workspace_id uuid,
  target_kind text NOT NULL CHECK (target_kind IN ('DOCUMENT', 'WORKSPACE')),
  target_id uuid NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'RETRY', 'COMPLETED')),
  step text NOT NULL DEFAULT 'PENDING' CHECK (step IN ('PENDING', 'ACCESS_REVOKED', 'OBJECTS_CAPTURED', 'DOMAIN_PURGED', 'OBJECTS_PURGED', 'AUDIT_REDACTED', 'COMPLETED')),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  run_after timestamptz NOT NULL,
  lease_owner text,
  lease_until timestamptz,
  last_error_code text,
  started_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  completed_at timestamptz,
  result_hash text,
  UNIQUE (target_kind, target_id),
  CHECK ((lease_owner IS NULL) = (lease_until IS NULL)),
  CHECK ((status = 'COMPLETED') = (completed_at IS NOT NULL)),
  CHECK (result_hash IS NULL OR result_hash ~ '^[a-f0-9]{64}$')
);
CREATE INDEX purge_ledger_claim_idx ON purge_ledger (run_after, started_at, id)
  WHERE status IN ('PENDING', 'RETRY', 'RUNNING');

CREATE TABLE purge_object_deletions (
  ledger_id uuid NOT NULL REFERENCES purge_ledger(id) ON DELETE CASCADE,
  storage_key text NOT NULL CHECK (storage_key ~ '^[a-f0-9]{64}$'),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  last_error_code text,
  deleted_at timestamptz,
  PRIMARY KEY (ledger_id, storage_key)
);

CREATE FUNCTION reject_immutable_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF retention_mutation_allowed() AND TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'immutable history cannot be changed';
END;
$$;

CREATE TRIGGER published_versions_immutable
  BEFORE UPDATE OR DELETE ON published_versions
  FOR EACH ROW EXECUTE FUNCTION reject_immutable_row();
CREATE TRIGGER version_context_immutable
  BEFORE UPDATE OR DELETE ON version_context
  FOR EACH ROW EXECUTE FUNCTION reject_immutable_row();
CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND retention_mutation_allowed() AND
     NEW.id = OLD.id AND NEW.workspace_id = OLD.workspace_id AND NEW.sequence = OLD.sequence AND
     NEW.actor_json = OLD.actor_json AND NEW.action = OLD.action AND NEW.target_json = OLD.target_json AND
     NEW.correlation_id = OLD.correlation_id AND NEW.occurred_at = OLD.occurred_at AND
     NEW.redacted_at IS NOT NULL THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'audit_events is append-only';
END;
$$;
CREATE TRIGGER audit_events_immutable
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();

CREATE FUNCTION validate_permission_subject() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.subject_kind = 'USER' AND NOT EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.workspace_id = NEW.workspace_id AND m.user_id = NEW.subject_id AND m.status = 'ACTIVE'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'permission user must be an active workspace member';
  ELSIF NEW.subject_kind = 'GROUP' AND NOT EXISTS (
    SELECT 1 FROM groups g
    WHERE g.workspace_id = NEW.workspace_id AND g.id = NEW.subject_id AND g.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'permission group must be active in the workspace';
  END IF;
  RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER permission_subject_valid
  AFTER INSERT OR UPDATE ON permission_grants
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validate_permission_subject();

CREATE FUNCTION bump_workspace_permission_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  target_workspace_id uuid;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_workspace_id := OLD.workspace_id;
  ELSE
    target_workspace_id := NEW.workspace_id;
  END IF;
  INSERT INTO workspace_access_revisions(workspace_id, permission_revision, updated_at)
  SELECT target_workspace_id, 1, now()
  WHERE EXISTS (SELECT 1 FROM workspaces WHERE id = target_workspace_id)
  ON CONFLICT(workspace_id) DO UPDATE
    SET permission_revision = workspace_access_revisions.permission_revision + 1,
        updated_at = EXCLUDED.updated_at;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE FUNCTION bump_workspace_policy_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  target_workspace_id uuid;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_workspace_id := OLD.workspace_id;
  ELSE
    target_workspace_id := NEW.workspace_id;
  END IF;
  INSERT INTO workspace_access_revisions(workspace_id, policy_revision, updated_at)
  SELECT target_workspace_id, 1, now()
  WHERE EXISTS (SELECT 1 FROM workspaces WHERE id = target_workspace_id)
  ON CONFLICT(workspace_id) DO UPDATE
    SET policy_revision = workspace_access_revisions.policy_revision + 1,
        updated_at = EXCLUDED.updated_at;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER membership_permission_revision
  AFTER INSERT OR DELETE OR UPDATE OF status ON memberships
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER group_member_permission_revision
  AFTER INSERT OR DELETE OR UPDATE ON group_members
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER grant_permission_revision
  AFTER INSERT OR DELETE OR UPDATE ON permission_grants
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER document_permission_revision
  AFTER INSERT OR DELETE OR UPDATE OF parent_id, status ON documents
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER document_policy_revision
  AFTER INSERT OR DELETE OR UPDATE OF parent_id, status ON documents
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();
CREATE TRIGGER publish_policy_revision
  AFTER INSERT OR DELETE OR UPDATE ON publish_policies
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();
CREATE TRIGGER workspace_default_policy_revision
  AFTER UPDATE OF default_publish_mode ON workspaces
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();

COMMIT;
