-- document-id: DATA-07
-- PostgreSQL 16 canonical bootstrap schema. UUIDv7 values are generated by the application.

BEGIN;

CREATE TYPE workspace_status AS ENUM ('ACTIVE', 'DELETION_SCHEDULED', 'PURGING', 'DELETED');
CREATE TYPE membership_role AS ENUM ('MEMBER', 'ADMIN', 'OWNER');
CREATE TYPE membership_status AS ENUM ('ACTIVE', 'SUSPENDED', 'REMOVED');
CREATE TYPE subject_kind AS ENUM ('USER', 'GROUP');
CREATE TYPE document_access AS ENUM ('NO_ACCESS', 'VIEWER', 'CONTRIBUTOR', 'EDITOR');
CREATE TYPE document_status AS ENUM ('ACTIVE', 'TRASHED', 'PURGING');
CREATE TYPE publish_mode AS ENUM ('DIRECT', 'REVIEW_REQUIRED');
CREATE TYPE discussion_status AS ENUM ('OPEN', 'CLOSED');
CREATE TYPE review_status AS ENUM ('REQUESTED', 'APPROVED', 'CHANGES_REQUESTED', 'CANCELLED', 'INVALIDATED');
CREATE TYPE review_decision AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUESTED');
CREATE TYPE vocabulary_status AS ENUM ('ACTIVE', 'DEPRECATED');
CREATE TYPE ai_job_status AS ENUM ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT');
CREATE TYPE proposal_status AS ENUM ('OPEN', 'APPLIED', 'REJECTED', 'STALE', 'CANCELLED');
CREATE TYPE file_status AS ENUM ('UPLOADING', 'READY', 'FAILED', 'DELETED');
CREATE TYPE job_status AS ENUM ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'DEAD_LETTER');

CREATE TABLE users (
  id uuid PRIMARY KEY,
  identity_issuer text NOT NULL DEFAULT 'https://accounts.google.com',
  google_subject text NOT NULL,
  email text NOT NULL,
  email_normalized text GENERATED ALWAYS AS (lower(email)) STORED,
  display_name text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 200),
  locale text NOT NULL DEFAULT 'ko' CHECK (locale IN ('ko', 'en')),
  timezone text NOT NULL DEFAULT 'Asia/Seoul',
  theme text NOT NULL DEFAULT 'SYSTEM' CHECK (theme IN ('LIGHT', 'DARK', 'SYSTEM')),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (identity_issuer, google_subject)
);
CREATE INDEX users_email_normalized_idx ON users (email_normalized);

CREATE TABLE login_flows (
  state_hash bytea PRIMARY KEY CHECK (octet_length(state_hash) = 32),
  marker_hash bytea NOT NULL CHECK (octet_length(marker_hash) = 32),
  hash_key_id text NOT NULL CHECK (hash_key_id ~ '^[A-Za-z0-9._-]{1,64}$'),
  nonce_hash bytea NOT NULL CHECK (octet_length(nonce_hash) = 32),
  pkce_verifier text NOT NULL CHECK (char_length(pkce_verifier) BETWEEN 43 AND 128),
  return_to text NOT NULL CHECK (char_length(return_to) BETWEEN 1 AND 2048),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  CHECK (expires_at > created_at),
  CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE INDEX login_flows_expiry_idx ON login_flows (expires_at);

CREATE TABLE sessions (
  id_hash bytea PRIMARY KEY CHECK (octet_length(id_hash) = 32),
  hash_key_id text NOT NULL CHECK (hash_key_id ~ '^[A-Za-z0-9._-]{1,64}$'),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rotated_from_hash bytea UNIQUE,
  last_seen_at timestamptz NOT NULL,
  idle_expires_at timestamptz NOT NULL,
  absolute_expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (last_seen_at >= created_at),
  CHECK (idle_expires_at >= last_seen_at),
  CHECK (absolute_expires_at >= idle_expires_at),
  CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX sessions_active_user_idx ON sessions (user_id, idle_expires_at, absolute_expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE user_command_receipts (
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operation_id text NOT NULL CHECK (char_length(operation_id) BETWEEN 1 AND 100),
  key text NOT NULL CHECK (char_length(key) BETWEEN 16 AND 128),
  request_hash text NOT NULL CHECK (request_hash ~ '^[a-f0-9]{64}$'),
  response_json jsonb,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (user_id, operation_id, key),
  CHECK (expires_at > created_at)
);
CREATE INDEX user_command_receipts_expiry_idx ON user_command_receipts (expires_at);

CREATE TABLE workspaces (
  id uuid PRIMARY KEY,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
  status workspace_status NOT NULL DEFAULT 'ACTIVE',
  default_publish_mode publish_mode NOT NULL DEFAULT 'DIRECT',
  delete_after timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'ACTIVE' AND delete_after IS NULL) OR
         (status IN ('DELETION_SCHEDULED', 'PURGING', 'DELETED') AND delete_after IS NOT NULL))
);

CREATE TABLE memberships (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role membership_role NOT NULL DEFAULT 'MEMBER',
  status membership_status NOT NULL DEFAULT 'ACTIVE',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  joined_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  PRIMARY KEY (workspace_id, user_id),
  CHECK ((status = 'REMOVED') = (removed_at IS NOT NULL))
);
CREATE INDEX memberships_active_user_idx ON memberships (user_id, workspace_id) WHERE status = 'ACTIVE';

CREATE TABLE writing_configurations (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  baseline_version text NOT NULL,
  overrides_json jsonb NOT NULL,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE ai_configurations (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  provider text NOT NULL,
  model text NOT NULL,
  user_concurrency_limit smallint NOT NULL CHECK (user_concurrency_limit BETWEEN 1 AND 20),
  workspace_concurrency_limit smallint NOT NULL CHECK (workspace_concurrency_limit BETWEEN 1 AND 200),
  monthly_budget_microunits bigint NOT NULL CHECK (monthly_budget_microunits >= 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (user_concurrency_limit <= workspace_concurrency_limit)
);

CREATE TABLE ai_usage_daily (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  estimated_microunits bigint NOT NULL DEFAULT 0 CHECK (estimated_microunits >= 0),
  job_count bigint NOT NULL DEFAULT 0 CHECK (job_count >= 0),
  PRIMARY KEY (workspace_id, usage_date, provider, model)
);

CREATE TABLE invitations (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email text NOT NULL,
  email_normalized text GENERATED ALWAYS AS (lower(email)) STORED,
  role membership_role NOT NULL DEFAULT 'MEMBER' CHECK (role <> 'OWNER'),
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  token_key_id text NOT NULL CHECK (char_length(token_key_id) BETWEEN 1 AND 64),
  invited_by uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, invited_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (expires_at > created_at),
  CHECK (accepted_at IS NULL OR revoked_at IS NULL)
);
CREATE UNIQUE INDEX invitations_active_email_idx ON invitations (workspace_id, email_normalized)
  WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE TABLE groups (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
  name_normalized text GENERATED ALWAYS AS (lower(name)) STORED,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id)
);
CREATE UNIQUE INDEX groups_active_name_idx ON groups (workspace_id, name_normalized) WHERE deleted_at IS NULL;

CREATE TABLE group_members (
  workspace_id uuid NOT NULL,
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, group_id, user_id),
  FOREIGN KEY (workspace_id, group_id) REFERENCES groups(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE
);

CREATE TABLE documents (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  parent_id uuid,
  rank text COLLATE "C" NOT NULL CHECK (rank ~ '^[0-9A-Za-z]{32}$'),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
  status document_status NOT NULL DEFAULT 'ACTIVE',
  current_version_id uuid,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  permission_revision bigint NOT NULL DEFAULT 0 CHECK (permission_revision >= 0),
  policy_revision bigint NOT NULL DEFAULT 0 CHECK (policy_revision >= 0),
  trashed_at timestamptz,
  purge_after timestamptz,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, parent_id) REFERENCES documents(workspace_id, id) DEFERRABLE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (parent_id IS NULL OR parent_id <> id),
  CHECK ((status = 'ACTIVE' AND trashed_at IS NULL AND purge_after IS NULL) OR
         (status IN ('TRASHED', 'PURGING') AND trashed_at IS NOT NULL AND purge_after IS NOT NULL)),
  CHECK (purge_after IS NULL OR purge_after >= trashed_at)
);
CREATE UNIQUE INDEX documents_sibling_rank_idx ON documents (workspace_id, parent_id, rank) WHERE status <> 'PURGING';
CREATE INDEX documents_tree_idx ON documents (workspace_id, parent_id, status, rank);

CREATE TABLE workspace_document_revisions (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  tree_revision bigint NOT NULL DEFAULT 0 CHECK (tree_revision >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE FUNCTION initialize_workspace_document_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO workspace_document_revisions(workspace_id) VALUES(NEW.id);
  RETURN NEW;
END;
$$;
CREATE TRIGGER workspace_document_revision_initialize
  AFTER INSERT ON workspaces
  FOR EACH ROW EXECUTE FUNCTION initialize_workspace_document_revision();

CREATE TABLE document_move_previews (
  token_hash bytea PRIMARY KEY CHECK (octet_length(token_hash) = 32),
  workspace_id uuid NOT NULL,
  actor_user_id uuid NOT NULL,
  document_id uuid NOT NULL,
  claims_json jsonb NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, actor_user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  CHECK (jsonb_typeof(claims_json) = 'object'),
  CHECK (expires_at > created_at)
);
CREATE INDEX document_move_previews_expiry_idx ON document_move_previews (expires_at);

CREATE TABLE workspace_access_revisions (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  permission_revision bigint NOT NULL DEFAULT 0 CHECK (permission_revision >= 0),
  policy_revision bigint NOT NULL DEFAULT 0 CHECK (policy_revision >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE permission_grants (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  subject_kind subject_kind NOT NULL,
  subject_id uuid NOT NULL,
  access document_access NOT NULL,
  can_manage boolean NOT NULL DEFAULT false,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  granted_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, document_id, subject_kind, subject_id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, granted_by) REFERENCES memberships(workspace_id, user_id),
  CHECK (NOT can_manage OR access = 'EDITOR')
);
CREATE INDEX permission_grants_resolve_idx ON permission_grants (workspace_id, subject_kind, subject_id, document_id);

CREATE TABLE publish_policies (
  document_id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  mode publish_mode NOT NULL,
  required_approvals smallint NOT NULL DEFAULT 0 CHECK (required_approvals BETWEEN 0 AND 20),
  reviewer_rule jsonb NOT NULL DEFAULT '{"kind":"ANY_EDITOR"}'::jsonb,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((mode = 'DIRECT' AND required_approvals = 0) OR (mode = 'REVIEW_REQUIRED' AND required_approvals > 0))
);

CREATE TABLE published_versions (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  number bigint NOT NULL CHECK (number > 0),
  content_json jsonb NOT NULL,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  publisher_id uuid NOT NULL,
  summary text NOT NULL DEFAULT '' CHECK (char_length(summary) <= 2000),
  published_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  UNIQUE (document_id, number),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (workspace_id, publisher_id) REFERENCES memberships(workspace_id, user_id)
);
ALTER TABLE documents ADD CONSTRAINT documents_current_version_fk
  FOREIGN KEY (workspace_id, current_version_id) REFERENCES published_versions(workspace_id, id) DEFERRABLE;

CREATE TABLE drafts (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL UNIQUE,
  base_version_id uuid,
  content_json jsonb NOT NULL,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, base_version_id) REFERENCES published_versions(workspace_id, id),
  FOREIGN KEY (workspace_id, updated_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE edit_leases (
  document_id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  holder_user_id uuid NOT NULL,
  client_instance_id uuid NOT NULL,
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at timestamptz NOT NULL,
  released_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  acquired_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, holder_user_id) REFERENCES memberships(workspace_id, user_id),
  CHECK (released_at IS NULL OR released_at >= acquired_at)
);
CREATE INDEX edit_leases_expiry_idx ON edit_leases (expires_at);

CREATE TABLE version_context (
  version_id uuid PRIMARY KEY REFERENCES published_versions(id) ON DELETE CASCADE,
  review_snapshot_json jsonb NOT NULL,
  discussion_ids uuid[] NOT NULL DEFAULT '{}',
  source_revision bigint NOT NULL CHECK (source_revision >= 0)
);

CREATE TABLE public_links (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at timestamptz,
  revoked_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id)
);
CREATE INDEX public_links_active_document_idx ON public_links (workspace_id, document_id)
  WHERE revoked_at IS NULL;

CREATE TABLE discussions (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
  status discussion_status NOT NULL DEFAULT 'OPEN',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status = 'CLOSED') = (closed_at IS NOT NULL))
);
CREATE INDEX discussions_document_idx ON discussions (workspace_id, document_id, status, created_at DESC);

CREATE TABLE discussion_topics (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  discussion_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind IN ('TEXT', 'DOCUMENT', 'REGION', 'EXTERNAL')),
  target_json jsonb NOT NULL,
  label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 500),
  rank text NOT NULL,
  UNIQUE (discussion_id, rank),
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  discussion_id uuid NOT NULL,
  author_id uuid NOT NULL,
  body_json jsonb NOT NULL,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, author_id) REFERENCES memberships(workspace_id, user_id)
);
CREATE INDEX messages_discussion_idx ON messages (workspace_id, discussion_id, created_at, id);

CREATE TABLE message_revisions (
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  revision bigint NOT NULL CHECK (revision > 0),
  body_json jsonb NOT NULL,
  edited_by uuid NOT NULL REFERENCES users(id),
  edited_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, revision)
);

CREATE TABLE reviews (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  draft_id uuid NOT NULL,
  draft_revision bigint NOT NULL CHECK (draft_revision >= 0),
  policy_snapshot_json jsonb NOT NULL,
  status review_status NOT NULL DEFAULT 'REQUESTED',
  requested_by uuid NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, draft_id) REFERENCES drafts(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, requested_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status = 'REQUESTED') = (resolved_at IS NULL))
);
CREATE UNIQUE INDEX reviews_active_document_idx ON reviews (document_id) WHERE status IN ('REQUESTED', 'APPROVED');

CREATE TABLE review_assignments (
  workspace_id uuid NOT NULL,
  review_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  decision review_decision NOT NULL DEFAULT 'PENDING',
  decided_at timestamptz,
  discussion_id uuid,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (review_id, reviewer_id),
  FOREIGN KEY (workspace_id, review_id) REFERENCES reviews(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, reviewer_id) REFERENCES memberships(workspace_id, user_id),
  FOREIGN KEY (workspace_id, discussion_id) REFERENCES discussions(workspace_id, id),
  CHECK ((decision = 'PENDING') = (decided_at IS NULL))
);

CREATE TABLE inbox_items (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL,
  source_key text NOT NULL,
  target_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  resolved_at timestamptz,
  UNIQUE (workspace_id, user_id, source_key),
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id) ON DELETE CASCADE
);
CREATE INDEX inbox_items_unresolved_idx ON inbox_items (workspace_id, user_id, created_at DESC)
  WHERE resolved_at IS NULL;

CREATE TABLE references_graph (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  source_kind text NOT NULL,
  source_id uuid NOT NULL,
  target_kind text NOT NULL,
  target_id text NOT NULL,
  source_region_json jsonb,
  snapshot_json jsonb NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id),
  UNIQUE (workspace_id, source_kind, source_id, target_kind, target_id)
);
CREATE INDEX references_target_idx ON references_graph (workspace_id, target_kind, target_id);

CREATE TABLE vocabulary_concepts (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  canonical_term text NOT NULL CHECK (char_length(canonical_term) BETWEEN 1 AND 200),
  definition text NOT NULL CHECK (char_length(definition) BETWEEN 1 AND 5000),
  status vocabulary_status NOT NULL DEFAULT 'ACTIVE',
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, created_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE vocabulary_terms (
  workspace_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  term text NOT NULL,
  normalized_term text GENERATED ALWAYS AS (lower(btrim(term))) STORED,
  kind text NOT NULL CHECK (kind IN ('CANONICAL', 'SYNONYM', 'PROHIBITED')),
  PRIMARY KEY (concept_id, normalized_term),
  FOREIGN KEY (workspace_id, concept_id) REFERENCES vocabulary_concepts(workspace_id, id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX vocabulary_terms_workspace_unique_idx ON vocabulary_terms (workspace_id, normalized_term);

CREATE TABLE ai_jobs (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL,
  target_json jsonb NOT NULL,
  expected_revision bigint NOT NULL CHECK (expected_revision >= 0),
  status ai_job_status NOT NULL DEFAULT 'QUEUED',
  priority smallint NOT NULL CHECK (priority BETWEEN 0 AND 100),
  provider text NOT NULL,
  model text NOT NULL,
  usage_json jsonb,
  error_code text,
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')) = (completed_at IS NOT NULL))
);
CREATE INDEX ai_jobs_queue_idx ON ai_jobs (priority DESC, created_at) WHERE status = 'QUEUED';
CREATE INDEX ai_jobs_user_active_idx ON ai_jobs (workspace_id, user_id, status)
  WHERE status IN ('QUEUED', 'RUNNING');

CREATE TABLE ai_context_sources (
  job_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  source_kind text NOT NULL,
  source_id text NOT NULL,
  authority text NOT NULL,
  snapshot_hash text NOT NULL CHECK (snapshot_hash ~ '^[a-f0-9]{64}$'),
  included boolean NOT NULL,
  metadata_json jsonb NOT NULL,
  PRIMARY KEY (job_id, ordinal),
  FOREIGN KEY (workspace_id, job_id) REFERENCES ai_jobs(workspace_id, id) ON DELETE CASCADE
);

CREATE TABLE ai_results (
  job_id uuid PRIMARY KEY REFERENCES ai_jobs(id) ON DELETE CASCADE,
  schema_version integer NOT NULL CHECK (schema_version > 0),
  result_json jsonb NOT NULL,
  validation_json jsonb NOT NULL,
  completed_at timestamptz NOT NULL
);

CREATE TABLE proposals (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  job_id uuid NOT NULL UNIQUE,
  document_id uuid NOT NULL,
  base_revision bigint NOT NULL CHECK (base_revision >= 0),
  operations_json jsonb NOT NULL,
  status proposal_status NOT NULL DEFAULT 'OPEN',
  applied_revision bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  FOREIGN KEY (workspace_id, job_id) REFERENCES ai_jobs(workspace_id, id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, document_id) REFERENCES documents(workspace_id, id) ON DELETE CASCADE,
  CHECK ((status = 'OPEN') = (resolved_at IS NULL)),
  CHECK ((status = 'APPLIED') = (applied_revision IS NOT NULL))
);

CREATE TABLE file_assets (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  storage_key text NOT NULL,
  original_name text NOT NULL CHECK (char_length(original_name) BETWEEN 1 AND 500),
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  checksum_sha256 text NOT NULL CHECK (checksum_sha256 ~ '^[a-f0-9]{64}$'),
  status file_status NOT NULL DEFAULT 'UPLOADING',
  uploaded_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  ready_at timestamptz,
  deleted_at timestamptz,
  purge_after timestamptz,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (id),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, storage_key),
  FOREIGN KEY (workspace_id, uploaded_by) REFERENCES memberships(workspace_id, user_id),
  CHECK ((status IN ('UPLOADING', 'FAILED') AND ready_at IS NULL) OR
         (status IN ('READY', 'DELETED') AND ready_at IS NOT NULL)),
  CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL AND purge_after IS NOT NULL))
);
CREATE INDEX file_assets_gc_idx ON file_assets (workspace_id, purge_after) WHERE status = 'DELETED';

CREATE TABLE file_references (
  workspace_id uuid NOT NULL,
  asset_id uuid NOT NULL,
  owner_kind text NOT NULL CHECK (owner_kind IN ('DRAFT', 'PUBLISHED_VERSION', 'MESSAGE', 'VOCABULARY')),
  owner_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (asset_id, owner_kind, owner_id),
  FOREIGN KEY (workspace_id, asset_id) REFERENCES file_assets(workspace_id, id) ON DELETE CASCADE
);
CREATE INDEX file_references_owner_idx ON file_references (workspace_id, owner_kind, owner_id);

CREATE TABLE workspace_sequences (
  workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,
  next_audit_sequence bigint NOT NULL DEFAULT 1 CHECK (next_audit_sequence > 0)
);

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  sequence bigint NOT NULL CHECK (sequence > 0),
  actor_json jsonb NOT NULL,
  action text NOT NULL,
  target_json jsonb NOT NULL,
  metadata_json jsonb NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, sequence)
);
CREATE INDEX audit_events_target_idx ON audit_events (workspace_id, (target_json->>'kind'), (target_json->>'id'), sequence DESC);

CREATE TABLE jobs (
  id uuid PRIMARY KEY,
  workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE,
  kind text NOT NULL,
  payload_json jsonb NOT NULL,
  status job_status NOT NULL DEFAULT 'QUEUED',
  priority smallint NOT NULL DEFAULT 50 CHECK (priority BETWEEN 0 AND 100),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  run_after timestamptz NOT NULL DEFAULT now(),
  lease_owner text,
  lease_until timestamptz,
  last_error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CHECK ((lease_owner IS NULL) = (lease_until IS NULL)),
  CHECK (attempt <= max_attempts),
  CHECK ((status IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'DEAD_LETTER')) = (completed_at IS NOT NULL))
);
CREATE INDEX jobs_dequeue_idx ON jobs (priority DESC, run_after, id) WHERE status = 'QUEUED';

CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  aggregate_kind text NOT NULL,
  aggregate_id uuid NOT NULL,
  sequence bigint NOT NULL CHECK (sequence > 0),
  event_type text NOT NULL,
  event_version integer NOT NULL CHECK (event_version > 0),
  payload_json jsonb NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  UNIQUE (aggregate_kind, aggregate_id, sequence)
);
CREATE INDEX outbox_unpublished_idx ON outbox_events (occurred_at, id) WHERE published_at IS NULL;

CREATE TABLE consumer_receipts (
  consumer text NOT NULL,
  event_id uuid NOT NULL REFERENCES outbox_events(id) ON DELETE CASCADE,
  processed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (consumer, event_id)
);

CREATE TABLE idempotency_keys (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES users(id),
  operation_id text NOT NULL,
  key text NOT NULL,
  request_hash text NOT NULL CHECK (request_hash ~ '^[a-f0-9]{64}$'),
  response_status integer,
  response_json jsonb,
  locked_until timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, actor_id, operation_id, key),
  CHECK ((response_status IS NULL) = (response_json IS NULL)),
  CHECK (expires_at > created_at)
);
CREATE INDEX idempotency_expiry_idx ON idempotency_keys (expires_at);

CREATE TABLE purge_ledger (
  id uuid PRIMARY KEY,
  workspace_id uuid,
  target_kind text NOT NULL,
  target_id uuid NOT NULL,
  reason text NOT NULL,
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  result_hash text,
  UNIQUE (target_kind, target_id)
);

CREATE FUNCTION reject_immutable_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF current_user = 'adoc_retention' THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = TG_TABLE_NAME || ' is append-only';
END;
$$;

CREATE TRIGGER published_versions_immutable
  BEFORE UPDATE OR DELETE ON published_versions
  FOR EACH ROW EXECUTE FUNCTION reject_immutable_row();
CREATE TRIGGER version_context_immutable
  BEFORE UPDATE OR DELETE ON version_context
  FOR EACH ROW EXECUTE FUNCTION reject_immutable_row();
CREATE TRIGGER audit_events_immutable
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_immutable_row();

CREATE FUNCTION validate_permission_subject() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.subject_kind = 'USER' AND NOT EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.workspace_id = NEW.workspace_id AND m.user_id = NEW.subject_id AND m.status = 'ACTIVE'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'permission user must be an active workspace member';
  ELSIF NEW.subject_kind = 'GROUP' AND NOT EXISTS (
    SELECT 1 FROM groups g
    WHERE g.workspace_id = NEW.workspace_id AND g.id = NEW.subject_id AND g.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'permission group must be active in the workspace';
  END IF;
  RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER permission_subject_valid
  AFTER INSERT OR UPDATE ON permission_grants
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validate_permission_subject();

CREATE FUNCTION bump_workspace_permission_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  target_workspace_id uuid;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_workspace_id := OLD.workspace_id;
  ELSE
    target_workspace_id := NEW.workspace_id;
  END IF;
  INSERT INTO workspace_access_revisions(workspace_id, permission_revision, updated_at)
  SELECT target_workspace_id, 1, now()
  WHERE EXISTS (SELECT 1 FROM workspaces WHERE id = target_workspace_id)
  ON CONFLICT(workspace_id) DO UPDATE
    SET permission_revision = workspace_access_revisions.permission_revision + 1,
        updated_at = EXCLUDED.updated_at;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE FUNCTION bump_workspace_policy_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  target_workspace_id uuid;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_workspace_id := OLD.workspace_id;
  ELSE
    target_workspace_id := NEW.workspace_id;
  END IF;
  INSERT INTO workspace_access_revisions(workspace_id, policy_revision, updated_at)
  SELECT target_workspace_id, 1, now()
  WHERE EXISTS (SELECT 1 FROM workspaces WHERE id = target_workspace_id)
  ON CONFLICT(workspace_id) DO UPDATE
    SET policy_revision = workspace_access_revisions.policy_revision + 1,
        updated_at = EXCLUDED.updated_at;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER membership_permission_revision
  AFTER INSERT OR DELETE OR UPDATE OF status ON memberships
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER group_member_permission_revision
  AFTER INSERT OR DELETE OR UPDATE ON group_members
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER grant_permission_revision
  AFTER INSERT OR DELETE OR UPDATE ON permission_grants
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER document_permission_revision
  AFTER INSERT OR DELETE OR UPDATE OF parent_id, status ON documents
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_permission_revision();
CREATE TRIGGER document_policy_revision
  AFTER INSERT OR DELETE OR UPDATE OF parent_id, status ON documents
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();
CREATE TRIGGER publish_policy_revision
  AFTER INSERT OR DELETE OR UPDATE ON publish_policies
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();
CREATE TRIGGER workspace_default_policy_revision
  AFTER UPDATE OF default_publish_mode ON workspaces
  FOR EACH ROW EXECUTE FUNCTION bump_workspace_policy_revision();

COMMIT;
